# N ..dependencies:
name: prowess_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  location: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.4.0
  firebase_database: ^9.0.8
  firebase_core: ^1.13.1
  rxdart: ^0.27.2
  provider: ^6.0.0
  path_provider: ^2.0.9
  cloud_firestore:
    ^2.3.0
  firebase_auth: ^3.1.4
  flutter_signin_button: ^2.0.0
  google_maps_flutter: ^2.1.0
  url_launcher: ^6.0.0-nullsafety
  http: ^0.13.4
  emojis: ^0.9.9
  google_fonts: ^2.1.0
  mailer: ^5.1.0
  google_sign_in: ^5.2.3
  cloudinary_public: ^0.11.0
  image_picker: ^0.8.4+8
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.3.1

flutter_native_splash:
  color: "#f1ecc3"
  image: assets/images/ic_launcher.png
  ios: true
  android: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/data/

